version: '3.7'

volumes:
    lychee-images:

services:
    lychee:
        build: .
        ports:
            - 8080:80
        volumes:
            - ./content/nginx.conf:/etc/nginx/nginx.conf
            - ./.env:/var/www/Lychee/.env
            - lychee-images:/var/www/Lychee/public/uploads/
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}